apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: devportal-core-ds-paid-master-certs
  namespace: dpo-paid
  labels:
    app: devportal-core-ds-paid-master
data:
  {{- $certs := lookup "v1" "Secret" "dpo-paid" "devportal-core-ds-paid-master-certs" -}}
  {{- if $certs }}
    tls.crt: {{ index $certs.data "tls.crt" }}
    tls.key: {{ index $certs.data "tls.key" }}
    ca.crt: {{ index $certs.data "ca.crt" }}
  {{- else }}
    {{- $altNames := list "devportal-core-ds-paid-master" "devportal-core-ds-paid-master.dpo-paid" "devportal-core-ds-paid-master.dpo-paid.svc" -}}
    {{- $ca := genCA "opensearch-ca" 365 -}}
    {{- $cert := genSignedCert "devportal-core-ds-paid-master" nil $altNames 365 $ca -}}
    tls.crt: {{ $cert.Cert | toString | b64enc }}
    tls.key: {{ $cert.Key | toString | b64enc }}
    ca.crt: {{ $ca.Cert | toString | b64enc }}
  {{- end }}
